version: '3.8'

services:
  web:
    build:
      context: .
      target: ${DOCKER_BUILD_TARGET:-prod} # Default to prod if not set
    environment:
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_HOST}
      NODE_ENV: ${NODE_ENV:-production} # Default to production if not set
    ports:
      - 3000:3000
    restart: always

volumes:
  node_modules:
